name: e2e
on:
  workflow_dispatch:
    inputs:
      url:
        description: deployed url
        required: true
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/cypress-io/github-action
      - name: Cypress run üèÉ‚Äç‚ôÄÔ∏è
        uses: cypress-io/github-action@v4.1.1
        with:
          env: MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}
          install: true
          browser: chrome
          record: true
          config: baseUrl=${{ github.event.inputs.url }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
