name: Scheduled CMS login

# Controls when the workflow will run
on:
  # Triggers the workflow at 00:00 on Sunday.
  schedule:
    - cron: "0 0 * * 0"
jobs:
  cms-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run üèÉ‚Äç‚ôÄÔ∏è
        uses: cypress-io/github-action@v4.1.1
        with:
          spec: cypress/e2e/cms.cy.ts
          env: MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }},CMS_CYPRESS_USERNAME=${{ secrets.CMS_CYPRESS_USERNAME }},CMS_CYPRESS_PASSWORD=${{ secrets.CMS_CYPRESS_PASSWORD }}
          install: true
          browser: chrome
          record: false
          config: baseUrl=https://dev.churchinsydney.org
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
